// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4voycgTp7JFBG2Nwomzga0GR96tWXX40',
    appId: '1:320568980614:web:c36b0ea3853ba8b59d0d07',
    messagingSenderId: '320568980614',
    projectId: 'calculadora3d-stefan',
    authDomain: 'calculadora3d-stefan.firebaseapp.com',
    storageBucket: 'calculadora3d-stefan.firebasestorage.app',
    measurementId: 'G-LH0P8K31J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWGAakcnU9hv67OJOlcuCWgIt2w4tsId0',
    appId: '1:320568980614:android:a55b115d21bf1f819d0d07',
    messagingSenderId: '320568980614',
    projectId: 'calculadora3d-stefan',
    storageBucket: 'calculadora3d-stefan.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnho7XRnXteO-qA66q9TFxgcZksu2dgNg',
    appId: '1:320568980614:ios:608fe8429fb4f92b9d0d07',
    messagingSenderId: '320568980614',
    projectId: 'calculadora3d-stefan',
    storageBucket: 'calculadora3d-stefan.firebasestorage.app',
    iosBundleId: 'com.example.calculartor3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4voycgTp7JFBG2Nwomzga0GR96tWXX40',
    appId: '1:320568980614:web:c049736f7fd53a669d0d07',
    messagingSenderId: '320568980614',
    projectId: 'calculadora3d-stefan',
    authDomain: 'calculadora3d-stefan.firebaseapp.com',
    storageBucket: 'calculadora3d-stefan.firebasestorage.app',
    measurementId: 'G-LY93E6Z8YZ',
  );

}